/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package adsi;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Menu_Utama1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Pegawai = new javax.swing.JLabel();
        Supir = new javax.swing.JLabel();
        Kendaraan = new javax.swing.JLabel();
        jadwal = new javax.swing.JLabel();
        Laporan_Transaksi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 14, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/keluarr.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 701, -1, -1));

        Pegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pegawai.png"))); // NOI18N
        Pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PegawaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PegawaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PegawaiMouseReleased(evt);
            }
        });
        jPanel1.add(Pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        Supir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Supir.jpg"))); // NOI18N
        Supir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SupirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SupirMouseReleased(evt);
            }
        });
        jPanel1.add(Supir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        Kendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kendaraan.jpg"))); // NOI18N
        Kendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                KendaraanMouseReleased(evt);
            }
        });
        jPanel1.add(Kendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jadwal.jpg"))); // NOI18N
        jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jadwalMouseReleased(evt);
            }
        });
        jPanel1.add(jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        Laporan_Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/L_trans.png"))); // NOI18N
        Laporan_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Laporan_TransaksiMouseReleased(evt);
            }
        });
        jPanel1.add(Laporan_Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 450, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Travel Duta Prima Padang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 1130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        int keluar = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Akan Keluar?","Peringatan!", JOptionPane.YES_NO_OPTION);
        if (keluar==0){
            Login k = new Login();
            k.setVisible(true); 
            dispose();
        }else{
            return;
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void PegawaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PegawaiMouseReleased
        // TODO add your handling code here:
        //ImageIcon a = new ImageIcon(getClass().getResource("/image/Pegawai2.png"));
        //Pegawai.setIcon(a);
        
        Karyawan kar = new Karyawan();
        kar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PegawaiMouseReleased

    private void SupirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirMouseReleased
        // TODO add your handling code here:
        //ImageIcon a = new ImageIcon(getClass().getResource("/image/Supir2.png"));
        //Supir.setIcon(a);
        
        Pengemudi pem = new Pengemudi();
        pem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SupirMouseReleased

    private void KendaraanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanMouseReleased
        // TODO add your handling code here:
        Kendaraan Ken = new Kendaraan();
        Ken.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KendaraanMouseReleased

    private void jadwalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwalMouseReleased
        // TODO add your handling code here:
        Jadwal jad = new Jadwal();
        jad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jadwalMouseReleased

    private void Laporan_TransaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Laporan_TransaksiMouseReleased
        // TODO add your handling code here:
        Laporan_Transaksi LT = new Laporan_Transaksi();
        LT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Laporan_TransaksiMouseReleased

    private void PegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PegawaiMouseEntered
        // TODO add your handling code here:
        ImageIcon a = new ImageIcon(getClass().getResource("/image/Pegawai2.png"));
        Pegawai.setIcon(a);
    }//GEN-LAST:event_PegawaiMouseEntered

    private void PegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PegawaiMouseExited
        // TODO add your handling code here:
        //ImageIcon a = new ImageIcon(getClass().getResource("/image/Pegawai.png"));
        //Pegawai.setIcon(a);
    }//GEN-LAST:event_PegawaiMouseExited

    private void PegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PegawaiMousePressed
        // TODO add your handling code here:
        ImageIcon a = new ImageIcon(getClass().getResource("/image/Pegawai3.png"));
        Pegawai.setIcon(a);
    }//GEN-LAST:event_PegawaiMousePressed

    private void SupirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirMouseEntered
        // TODO add your handling code here:
        //ImageIcon a = new ImageIcon(getClass().getResource("/image/Supir2.png"));
        //Supir.setIcon(a);
    }//GEN-LAST:event_SupirMouseEntered

    private void SupirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirMouseExited
        // TODO add your handling code here:
        //ImageIcon a = new ImageIcon(getClass().getResource("/image/Supir.png"));
        //Supir.setIcon(a);
    }//GEN-LAST:event_SupirMouseExited

    private void SupirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirMousePressed
        // TODO add your handling code here:
        //ImageIcon a = new ImageIcon(getClass().getResource("/image/Supir3.png"));
        //Supir.setIcon(a);
    }//GEN-LAST:event_SupirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kendaraan;
    private javax.swing.JLabel Laporan_Transaksi;
    private javax.swing.JLabel Pegawai;
    private javax.swing.JLabel Supir;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jadwal;
    // End of variables declaration//GEN-END:variables
}
